### ISSUE TITLE
getDataByHashtags.py creating blank rows

### ISSUE THREAD

**Issue by p37307** [SamerAl-khateeb/MastodonDataCollection#1]
**_getDataByHashtags.py_** is creating blank rows in Windows because there is no lineterminator.

Line 42  `csvwriter = csv.writer(csv_output_file)` should be changed to `csvwriter = csv.writer(csv_output_file, lineterminator='\n')` .

**Comment by SamerAl-khateeb** [comment]
thank you for spotting this, I just fixed it!
